### ISSUE TITLE
Fingerprint on contacts page

### ISSUE THREAD

**Issue by deavmi** [Nutomic/ensichat#29] opened 2015-07-23 19:03 UTC
Wouldn't it be cool to show the fingerprint of the user under the bold text of the user, in like a gray text font.

![](https://github.com/Nutomic/ensichat/blob/master/graphics/screenshot_phone_2.png)

**Comment by deavmi** [comment] 2015-07-23 19:04
In this screen:

![](https://github.com/Nutomic/ensichat/blob/master/graphics/screenshot_phone_2.png)

**Comment by deavmi** [comment] 2015-07-23 19:46
Also an icon next to the contact showing their fingerprint on identical format. Or whatever the identical is based off of.

**Comment by Nutomic** [comment] 2015-07-23 22:26
That's where I just put the status. But we could show the fingerprint left of the username (like a profile picture).

Closing this as a duplicate of #27.

**Closed by Nutomic** 2015-07-23 22:26 UTC

**Comment by deavmi** [comment] 2015-07-24 04:25
Yeah okay.

Maybe later a profile page can be implemented.

Also is there a way to possibly click on that photo of the fingerprint to expand it too fils teen showing a text version of the fingerprint below the full screen identifiable in a dialog window.

**Comment by Nutomic** [comment] 2015-07-24 14:10
That's exactly my plan ;)

**Comment by deavmi** [comment] 2015-07-24 17:22
Yay! :smile:
